-- Composite signal indicators on tickers
ALTER TABLE tickers ADD COLUMN IF NOT EXISTS composite_score REAL NOT NULL DEFAULT 0;
ALTER TABLE tickers ADD COLUMN IF NOT EXISTS rsi_14 REAL NOT NULL DEFAULT 50;
ALTER TABLE tickers ADD COLUMN IF NOT EXISTS macd_line REAL NOT NULL DEFAULT 0;
ALTER TABLE tickers ADD COLUMN IF NOT EXISTS macd_signal_line REAL NOT NULL DEFAULT 0;
ALTER TABLE tickers ADD COLUMN IF NOT EXISTS macd_histogram REAL NOT NULL DEFAULT 0;
ALTER TABLE tickers ADD COLUMN IF NOT EXISTS roc_10 REAL NOT NULL DEFAULT 0;
ALTER TABLE tickers ADD COLUMN IF NOT EXISTS roc_20 REAL NOT NULL DEFAULT 0;
ALTER TABLE tickers ADD COLUMN IF NOT EXISTS volume_ratio REAL NOT NULL DEFAULT 1;

-- Lot grades
ALTER TABLE lots ADD COLUMN IF NOT EXISTS grade TEXT NOT NULL DEFAULT '';
ALTER TABLE lots ADD COLUMN IF NOT EXISTS grade_score REAL NOT NULL DEFAULT 0;
ALTER TABLE lots ADD COLUMN IF NOT EXISTS grade_explanation TEXT NOT NULL DEFAULT '';

-- Entry grade on positions
ALTER TABLE positions ADD COLUMN IF NOT EXISTS entry_grade TEXT NOT NULL DEFAULT 'C';
ALTER TABLE positions ADD COLUMN IF NOT EXISTS entry_grade_score REAL NOT NULL DEFAULT 50;
ALTER TABLE positions ADD COLUMN IF NOT EXISTS rsi_at_entry REAL NOT NULL DEFAULT 50;
ALTER TABLE positions ADD COLUMN IF NOT EXISTS bollinger_pct_at_entry REAL NOT NULL DEFAULT 50;
